name: CI

on:
  push:
    branches: [latest]
  pull_request:
    branches: [latest]

# Automatically cancel in-progress actions on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request_target' && github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        astro: [^3, ^4]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - run: npm i astro@${{ matrix.astro }}
      - run: npm i astro@${{ matrix.astro }}
        working-directory: packages.astro-og-canvas
      - run: npm i astro@${{ matrix.astro }}
        working-directory: demo

      - name: Test
        run: npm t
